import { LegalDocumentLayout } from "@/components/legal/LegalDocumentLayout";
import {
  LegalCallout,
  LegalH3,
  LegalLink,
  LegalOrderedList,
  LegalProseList,
  LegalSection,
} from "@/components/legal/LegalPageShell";
import { BRAND } from "@/lib/brand";
import {
  getLegalContactEmail,
  getLegalDisputeVenue,
  getLegalEntityName,
  getLegalGoverningLawJurisdiction,
  getLegalRegisteredAddress,
} from "@/lib/legal-site";
import { PRIVACY_POLICY_PATH, TERMS_OF_SERVICE_PATH } from "@/lib/legal-urls";
import { buildRouteMetadata } from "@/lib/cms/page-metadata";

export async function generateMetadata() {
  return buildRouteMetadata(TERMS_OF_SERVICE_PATH, {
    title: "Terms of Service",
    description: `Terms governing use of ${BRAND.name}.`,
  });
}

const TERMS_NAV = [
  { id: "agreement", label: "Agreement" },
  { id: "definitions", label: "Definitions" },
  { id: "service", label: "The Service" },
  { id: "eligibility", label: "Eligibility" },
  { id: "oauth", label: "OAuth & APIs" },
  { id: "acceptable-use", label: "Acceptable use" },
  { id: "ai", label: "AI outputs" },
  { id: "content", label: "Your content" },
  { id: "ip", label: "Intellectual property" },
  { id: "fees", label: "Fees & billing" },
  { id: "beta", label: "Beta features" },
  { id: "privacy-ref", label: "Privacy" },
  { id: "warranty", label: "Disclaimers" },
  { id: "liability", label: "Liability" },
  { id: "indemnity", label: "Indemnity" },
  { id: "termination", label: "Termination" },
  { id: "law", label: "Governing law" },
  { id: "disputes", label: "Disputes" },
  { id: "misc", label: "General" },
  { id: "contact", label: "Contact" },
];

export default function TermsOfServicePage() {
  const entity = getLegalEntityName();
  const email = getLegalContactEmail();
  const governingLaw = getLegalGoverningLawJurisdiction();
  const disputeVenue = getLegalDisputeVenue();
  const address = getLegalRegisteredAddress();

  return (
    <LegalDocumentLayout
      docKind="terms"
      title="Terms of Service"
      subtitle={`${BRAND.name} — please read carefully`}
      description={`These Terms of Service (“Terms”) govern your use of ${BRAND.name}, a conversational analytics service operated by ${entity} from Pune, Maharashtra, India. The Service lets you connect authorized marketing and advertising accounts (such as Google Analytics 4, Google Search Console, Google Ads, and Meta Ads, where supported) and interact with your data through AI-assisted features, subject to your plan and our product roadmap. By creating an account, accepting these Terms, signing in, or using the Service, you agree to them. If you use the Service for an organization, you represent that you have authority to bind that organization, and “you” includes that organization.`}
      navItems={TERMS_NAV}
    >
      <LegalSection id="agreement" title="1. Agreement and priority">
        <p>
          These Terms together with our{" "}
          <LegalLink href={PRIVACY_POLICY_PATH}>Privacy Policy</LegalLink> and any order form,
          statement of work, or enterprise agreement you enter into with us constitute the
          entire agreement regarding the Service, except where mandatory consumer law
          applies. If enterprise terms conflict with these Terms on the same subject, the
          enterprise terms control for that customer relationship.
        </p>
      </LegalSection>

      <LegalSection id="definitions" title="2. Definitions">
        <LegalProseList
          items={[
            <>
              <strong>“User Content”</strong> means text, files, prompts, configurations, or
              other materials you submit to the Service.
            </>,
            <>
              <strong>“Integration Data”</strong> means data retrieved from third-party
              platforms you connect via OAuth or similar authorization.
            </>,
            <>
              <strong>“Output”</strong> means content generated by the Service (including AI
              model responses, summaries, or visualizations) based on User Content and
              Integration Data.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection id="service" title="3. The Service">
        <p>
          {entity} provides {BRAND.name} to help you query, summarize, and visualize
          metrics from accounts you lawfully connect (OAuth and similar), using large
          language models and integrations available in your environment. Features,
          supported platforms, and models may change; we may add, modify, or retire
          functionality, perform maintenance, or adjust limits. We use commercially
          reasonable efforts to minimize disruption and, where appropriate, give advance
          notice of material deprecations.
        </p>
        <LegalH3>No guaranteed service levels</LegalH3>
        <p>
          Unless a separate written agreement expressly states otherwise, the Service is
          provided without a committed uptime or support SLA. Support channels and
          response targets, if any, are described on our website or in your order.
        </p>
      </LegalSection>

      <LegalSection id="eligibility" title="4. Eligibility and account security">
        <p>
          You must be able to form a legally binding contract in your jurisdiction and meet
          any minimum age required by applicable law and by connected platforms. You are
          responsible for the accuracy of registration information and for safeguarding
          credentials. Notify{" "}
          <LegalLink href={`mailto:${email}`}>{email}</LegalLink>{" "}
          promptly if you suspect unauthorized use. We may suspend accounts involved in
          suspected compromise until risks are mitigated.
        </p>
      </LegalSection>

      <LegalSection id="oauth" title="5. Third-party accounts, OAuth, and API policies">
        <p>
          Access to Google, Meta, LinkedIn, or other products requires your authorization
          and remains subject to each provider’s terms, developer policies, data use rules,
          and rate limits. You must:
        </p>
        <LegalOrderedList
          items={[
            "Use only accounts and data you are entitled to access;",
            "Not exceed granted scopes or misrepresent the Service in consent screens;",
            "Comply with the Google API Services User Data Policy (including Limited Use), Meta Platform Terms, LinkedIn API Terms, and analogous rules;",
            "Not use Integration Data in ways that violate those policies or applicable law (e.g. unlawful discrimination, spam, or deceptive ads).",
          ]}
        />
        <p>
          Providers may revoke tokens, change APIs, or enforce restrictions without notice
          to us. We are not liable for third-party actions, outages, or enforcement.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="6. Acceptable use">
        <p>You agree not to:</p>
        <LegalProseList
          items={[
            "Violate law or infringe others’ rights;",
            "Probe, scan, or attack the Service or other systems; circumvent security or access controls;",
            "Reverse engineer, decompile, or attempt to extract source code or model weights except where unwaivable law allows;",
            "Use the Service to build a competing product through systematic scraping of our UI, documentation, or non-public APIs;",
            "Overload the Service (e.g. abusive automation) or resell access without written permission;",
            "Upload malware, harass others, or distribute unlawful or harmful content;",
            "Use Outputs to make solely automated decisions with legal or similarly significant effects on individuals without safeguards required by law.",
          ]}
        />
        <p>
          We may investigate misuse, cooperate with platforms and authorities, and
          suspend or terminate access for violations.
        </p>
      </LegalSection>

      <LegalSection id="ai" title="7. AI-generated outputs">
        <p>
          Outputs are probabilistic and may be wrong, incomplete, or reflect biases in
          training data or prompts. You are solely responsible for evaluating Outputs and
          for decisions you make in reliance on them. The Service does not provide legal,
          tax, financial, medical, or other professional advice. For campaign or compliance
          decisions, verify figures in source platforms and consult qualified advisers.
        </p>
      </LegalSection>

      <LegalSection id="content" title="8. User Content and license to us">
        <p>
          You retain ownership of User Content. You grant {entity} a worldwide,
          non-exclusive, royalty-free license to host, process, transmit, display,
          reproduce, and create derivative works (such as formatted tables or charts){" "}
          <strong>solely</strong> to provide, secure, and improve the Service, enforce
          these Terms, and comply with law. This license ends when you delete the relevant
          User Content or your account, except for copies retained in backups, billing
          records, or as required by law.
        </p>
        <LegalH3>Your representations</LegalH3>
        <p>
          You represent that you have all rights necessary to submit User Content and to
          grant the license above, and that doing so does not violate third-party rights or
          agreements.
        </p>
      </LegalSection>

      <LegalSection id="ip" title="9. Our intellectual property and feedback">
        <p>
          The Service, including software, visual design, trademarks, and documentation (excluding your User Content), is owned by {entity} or its licensors. Except for the limited rights to use the Service under these Terms, no rights are granted to you.
        </p>
        <LegalH3>Feedback</LegalH3>
        <p>
          If you provide suggestions, ideas, or feedback about the Service, you grant us a
          perpetual, irrevocable, worldwide, royalty-free license to use and incorporate
          them without obligation to you, unless we agree otherwise in writing.
        </p>
      </LegalSection>

      <LegalSection id="fees" title="10. Fees, taxes, trials, and changes">
        <p>
          Paid plans, usage metering, and payment methods are described at checkout or in
          your order. Fees are stated exclusive of taxes unless noted; you are responsible
          for applicable taxes we are required to collect. Failure to pay may result in
          suspension or downgrade of features.
        </p>
        <LegalH3>Renewal and cancellation</LegalH3>
        <p>
          Subscriptions may renew automatically as disclosed at purchase. You may cancel
          according to the cancellation method we provide; cancellation typically takes
          effect at the end of the current billing period unless stated otherwise.
        </p>
        <LegalH3>Price changes</LegalH3>
        <p>
          We may change prices prospectively with reasonable notice where contractually
          permitted. Continued use after the effective date may constitute acceptance.
        </p>
        <LegalH3>Refunds</LegalH3>
        <p>
          Unless mandatory law or your order states otherwise, fees are non-refundable.
        </p>
      </LegalSection>

      <LegalSection id="beta" title="11. Beta and preview features">
        <p>
          We may offer beta, pilot, or preview features. They may be unstable, change
          frequently, or be withdrawn. They are provided <strong>as is</strong> without
          warranty. Do not rely on beta features for mission-critical or compliance
          workflows without independent validation.
        </p>
      </LegalSection>

      <LegalSection id="privacy-ref" title="12. Privacy">
        <p>
          Our <LegalLink href={PRIVACY_POLICY_PATH}>Privacy Policy</LegalLink> describes how we
          process personal data and is incorporated into these Terms by reference.
        </p>
      </LegalSection>

      <LegalSection id="warranty" title="13. Disclaimers">
        <p className="font-[family-name:var(--font-body)] text-[0.9rem] leading-relaxed text-white/80">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED “AS
          IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED,
          OR STATUTORY, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          TITLE, QUIET ENJOYMENT, ACCURACY, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT
          THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS, OR
          THAT INTEGRATIONS OR OUTPUTS WILL MEET YOUR REQUIREMENTS.
        </p>
        <p className="text-[0.875rem] text-white/55">
          Some jurisdictions limit disclaimers; in those places, disclaimers apply to the
          fullest extent allowed.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="14. Limitation of liability">
        <p className="font-[family-name:var(--font-body)] text-[0.9rem] leading-relaxed text-white/80">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL {entity}, ITS
          AFFILIATES, OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR SUPPLIERS BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR
          PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, GOODWILL, DATA, OR BUSINESS
          OPPORTUNITIES, ARISING OUT OF OR RELATED TO THE SERVICE OR THESE TERMS, EVEN IF
          ADVISED OF THE POSSIBILITY.
        </p>
        <p className="font-[family-name:var(--font-body)] text-[0.9rem] leading-relaxed text-white/80">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, OUR AGGREGATE LIABILITY FOR
          ALL CLAIMS RELATING TO THE SERVICE OR THESE TERMS WILL NOT EXCEED THE GREATER OF
          (A) THE FEES YOU PAID US FOR THE SERVICE IN THE TWELVE (12) MONTHS BEFORE THE
          CLAIM AROSE, OR (B) ONE HUNDRED U.S. DOLLARS (USD $100) IF NO FEES APPLIED.
        </p>
        <p className="text-[0.875rem] text-white/55">
          Nothing in these Terms excludes or limits liability that cannot be excluded or
          limited under applicable law (including death or personal injury caused by
          negligence, fraud, or willful misconduct where applicable).
        </p>
      </LegalSection>

      <LegalSection id="indemnity" title="15. Indemnity">
        <p>
          You will defend, indemnify, and hold harmless {entity} and its affiliates from
          and against any third-party claims, damages, losses, liabilities, costs, and
          expenses (including reasonable attorneys’ fees) arising out of or related to your
          User Content, Integration Data you cause to be processed, your use of the
          Service, your breach of these Terms, or your violation of law or third-party
          rights (including platform API terms).
        </p>
      </LegalSection>

      <LegalSection id="termination" title="16. Suspension and termination">
        <p>
          You may stop using the Service at any time. We may suspend or terminate access
          for breach, risk to security or others, extended non-payment, legal requirement,
          or cessation of the Service. Upon termination, your right to use the Service
          ceases; Sections intended to survive (including intellectual property,
          disclaimers, limitations, indemnity, governing law, and disputes) survive.
        </p>
        <LegalH3>Data after termination</LegalH3>
        <p>
          We may delete or retain data as described in the Privacy Policy and your
          enterprise agreement. Export your data before termination where the product
          allows.
        </p>
      </LegalSection>

      <LegalSection id="law" title="17. Governing law">
        <p>
          These Terms are governed by the laws of <strong>{governingLaw}</strong>,
          without regard to conflict-of-law rules that would apply another jurisdiction’s
          substantive laws, except that mandatory consumer or other protections in your
          country of residence remain unaffected where they cannot be waived.
        </p>
      </LegalSection>

      <LegalSection id="disputes" title="18. Dispute resolution">
        <p>
          Before filing a claim, contact us at{" "}
          <LegalLink href={`mailto:${email}`}>{email}</LegalLink>{" "}
          to seek an informal resolution. If a dispute is not resolved within a reasonable
          period (for example, thirty (30) days), either party may pursue remedies in the
          courts described below or as required by mandatory law.
        </p>
        <LegalH3>Venue</LegalH3>
        <p>
          Subject to non-waivable rights, you and {entity} agree that the courts at{" "}
          <strong>{disputeVenue}</strong> have exclusive jurisdiction and venue over
          disputes arising out of or relating to these Terms or the Service, except that{" "}
          {entity} may seek injunctive or equitable relief in any court of competent
          jurisdiction to protect intellectual property or confidential information.
        </p>
        <LegalH3>Class actions</LegalH3>
        <p>
          To the extent permitted by applicable law, proceedings may be conducted only on
          an individual basis, not as a class, consolidated, or representative action,
          unless you are in a jurisdiction that prohibits such waivers.
        </p>
      </LegalSection>

      <LegalSection id="misc" title="19. General">
        <LegalProseList
          items={[
            <>
              <strong>Export and sanctions.</strong> You may not use the Service in
              violation of export control or economic sanctions laws.
            </>,
            <>
              <strong>Assignment.</strong> You may not assign these Terms without our
              consent; we may assign them in connection with a merger, acquisition, or
              sale of assets.
            </>,
            <>
              <strong>Entire agreement; severability; waiver; force majeure.</strong> As
              described in standard commercial contracts — if a provision is invalid, the
              remainder remains; no waiver is implied from delay; we are not liable for
              delays beyond our reasonable control.
            </>,
            <>
              <strong>Electronic communications.</strong> You consent to receive notices
              electronically (including email and in-product messages).
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection id="contact" title="20. Contact">
        <p>For questions about these Terms or the Service, contact {entity}:</p>
        <LegalProseList
          items={[
            <>
              Email: <LegalLink href={`mailto:${email}`}>{email}</LegalLink>
            </>,
            <>
              Address:{" "}
              <span className="whitespace-pre-line">{address}</span>
            </>,
          ]}
        />
      </LegalSection>

      <LegalCallout variant="important" title="Legal disclaimer">
        These Terms set out the rules for using {BRAND.name}. They are{" "}
        <strong>not legal advice</strong>. If your situation involves regulated industries,
        employment, or complex cross-border issues, consider having counsel review your
        agreements and policies.
      </LegalCallout>
    </LegalDocumentLayout>
  );
}
